# Generated by Django 4.2.30 on 2026-06-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20)),
                ('mensajes', models.JSONField(default=list)),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_salida', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'conversación IA',
                'verbose_name_plural': 'conversaciones IA',
                'db_table': 'conversacion_ia',
            },
        ),
    ]
