# Generated by Django 4.2.30 on 2026-06-12 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        ('asistente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionia',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='negocios.establecimiento'),
        ),
    ]
