# Generated by Django 4.2.30 on 2026-09-02 12:32

from django.db import migrations, models


"""Marca de ultima actividad de la conversacion (RNF-09).

Las filas que ya existen reciben la fecha de la propia migracion, no la de
su ultimo mensaje real: `auto_now` no puede reconstruir el pasado. El efecto
practico es que, al desplegar, toda conversacion viva arranca su ventana de
caducidad de cero. Se acepta a proposito: la alternativa era rellenar con
`creado_en`, que caducaria de golpe conversaciones que quizas siguen
abiertas, y eso si se le nota al cliente.
"""


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionia',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
