# Generated by Django 4.2.30 on 2026-09-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0003_conversacionia_actualizado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionia',
            name='consentimiento_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversacionia',
            name='version_aviso',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
