# Generated by Django 4.2.30 on 2026-09-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0004_conversacionia_consentimiento_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionia',
            name='llamadas_modelo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
