# Generated by Django 4.2.30 on 2026-06-12 20:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('tipo', models.CharField(choices=[('barberia', 'Barbería'), ('salon', 'Salón de belleza / Peluquería'), ('unas', 'Servicio de uñas'), ('estetica', 'Centro de estética'), ('maquillaje', 'Maquillaje profesional'), ('masajes', 'Masajes y relajación'), ('spa', 'Spa integral'), ('mixto', 'Servicios mixtos')], max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('plan', models.CharField(choices=[('basico', 'Básico — 1 profesional'), ('estandar', 'Estándar — hasta 3 profesionales'), ('premium', 'Premium — hasta 6 profesionales')], default='basico', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'establecimiento',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='negocios.establecimiento')),
            ],
            options={
                'verbose_name_plural': 'profesionales',
                'db_table': 'profesional',
            },
        ),
        migrations.CreateModel(
            name='ProfesionalServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.profesional')),
            ],
            options={
                'db_table': 'profesional_servicio',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('duracion_min', models.PositiveSmallIntegerField(help_text='Duración en minutos; define el tamaño del slot (RN-03).', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio', models.DecimalField(decimal_places=0, help_text='Precio en pesos colombianos.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='negocios.establecimiento')),
                ('profesionales', models.ManyToManyField(related_name='servicios', through='negocios.ProfesionalServicio', to='negocios.profesional')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.AddField(
            model_name='profesionalservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.servicio'),
        ),
        migrations.CreateModel(
            name='HorarioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='negocios.profesional')),
            ],
            options={
                'db_table': 'horario_base',
            },
        ),
        migrations.CreateModel(
            name='ExcepcionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='negocios.profesional')),
            ],
            options={
                'db_table': 'excepcion_horario',
            },
        ),
        migrations.CreateModel(
            name='ClienteFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
                ('acepta_datos', models.BooleanField(help_text='Constancia de aceptación del aviso de privacidad (Ley 1581/2012).')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='negocios.establecimiento')),
            ],
            options={
                'db_table': 'cliente_final',
            },
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrente', models.BooleanField(default=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='negocios.profesional')),
            ],
            options={
                'db_table': 'bloqueo',
            },
        ),
        migrations.AddConstraint(
            model_name='profesionalservicio',
            constraint=models.UniqueConstraint(fields=('profesional', 'servicio'), name='uq_profesional_servicio'),
        ),
        migrations.AddConstraint(
            model_name='horariobase',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_horario_fin_mayor_inicio'),
        ),
        migrations.AddConstraint(
            model_name='excepcionhorario',
            constraint=models.UniqueConstraint(fields=('profesional', 'fecha'), name='uq_excepcion_profesional_fecha'),
        ),
        migrations.AddConstraint(
            model_name='excepcionhorario',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_excepcion_fin_mayor_inicio'),
        ),
        migrations.AddConstraint(
            model_name='clientefinal',
            constraint=models.UniqueConstraint(fields=('establecimiento', 'telefono'), name='uq_cliente_tenant_telefono'),
        ),
    ]
