# Generated by Django 4.2.30 on 2026-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_planes_a_dos_niveles'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='modo_agenda',
            field=models.CharField(choices=[('compacto', 'Compacto — sin huecos entre citas'), ('flexible', 'Flexible — horas cada 15 minutos')], default='compacto', help_text='Compacto: las citas se ofrecen pegadas una tras otra, sin dejar huecos inservibles. Flexible: se ofrecen cada 15 minutos, con mas opciones para el cliente a costa de fragmentar la agenda.', max_length=10),
        ),
    ]
