# Generated by Django 4.2.30 on 2026-08-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_establecimiento_modo_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='recordatorio_horas_antes',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 hora antes'), (2, '2 horas antes'), (4, '4 horas antes'), (12, '12 horas antes'), (24, '24 horas antes (el día anterior)'), (48, '48 horas antes')], default=2, help_text='Con cuánta antelación se avisa al cliente de su cita. Más antelación le da tiempo de cancelar y liberar el turno; menos reduce el riesgo de que se le olvide.'),
        ),
    ]
