# Generated by Django 4.2.30 on 2026-08-24 15:03

import django.core.validators
from django.db import migrations, models


def normalizar_nombres(apps, schema_editor):
    """Deja los nombres ya guardados en su forma canonica.

    Ahora que la identidad incluye el nombre, "wilson vergara" y "Wilson
    Vergara" serian dos clientes distintos. Se normaliza lo existente antes
    de aplicar la restriccion nueva.

    No puede haber colisiones: la restriccion anterior admitia una sola fila
    por (establecimiento, telefono), asi que despues de normalizar sigue
    habiendo como mucho una por telefono.
    """
    ClienteFinal = apps.get_model("negocios", "ClienteFinal")
    for cliente in ClienteFinal.objects.all():
        canonico = " ".join((cliente.nombre or "").split()).title()
        if canonico != cliente.nombre:
            cliente.nombre = canonico
            cliente.save(update_fields=["nombre"])


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_establecimiento_recordatorio_horas_antes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientefinal',
            name='uq_cliente_tenant_telefono',
        ),
        migrations.RunPython(normalizar_nombres,
                             migrations.RunPython.noop),
        migrations.AddField(
            model_name='establecimiento',
            name='max_citas_abiertas',
            field=models.PositiveSmallIntegerField(default=3, help_text='Cuántas citas futuras puede tener un mismo teléfono al tiempo. Evita que una sola persona acapare la agenda del día.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddConstraint(
            model_name='clientefinal',
            constraint=models.UniqueConstraint(fields=('establecimiento', 'telefono', 'nombre'), name='uq_cliente_tenant_telefono_nombre'),
        ),
    ]
