# Generated by Django 4.2.30 on 2026-08-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_remove_clientefinal_uq_cliente_tenant_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefonoBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos_bloqueados', to='negocios.establecimiento')),
            ],
            options={
                'db_table': 'telefono_bloqueado',
            },
        ),
        migrations.AddConstraint(
            model_name='telefonobloqueado',
            constraint=models.UniqueConstraint(fields=('establecimiento', 'telefono'), name='uq_bloqueo_tenant_telefono'),
        ),
    ]
