# Generated by Django 4.2.30 on 2026-08-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_telefonobloqueado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefinal',
            name='fecha_consentimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientefinal',
            name='version_aviso',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='municipio',
            field=models.CharField(default='', help_text='Municipio y departamento del negocio. Es el domicilio que exige la Ley 1581 para el aviso de privacidad del cliente final.', max_length=80),
        ),
    ]
