# Generated by Django 4.2.30 on 2026-08-26 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negocios', '0007_clientefinal_fecha_consentimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefinal',
            name='consentimiento_registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientefinal',
            name='origen_consentimiento',
            field=models.CharField(choices=[('autoservicio', 'El titular aceptó en la zona pública'), ('verbal_presencial', 'El dueño declara autorización verbal')], default='autoservicio', help_text='Cómo se obtuvo la autorización. Decide por dónde se entrega el recordatorio.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='clientefinal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('consentimiento_registrado_por__isnull', False), ('origen_consentimiento', 'verbal_presencial')), models.Q(('consentimiento_registrado_por__isnull', True), ('origen_consentimiento', 'autoservicio')), _connector='OR'), name='ck_consentimiento_origen_coherente'),
        ),
    ]
