# Generated by Django 4.2.30 on 2026-08-28 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0008_clientefinal_consentimiento_registrado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
    ]
