# Generated by Django 4.2.30 on 2026-09-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0010_materializar_asignaciones'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='excepcionhorario',
            name='uq_excepcion_profesional_fecha',
        ),
    ]
