# Generated by Django 4.2.30 on 2026-09-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0011_remove_excepcionhorario_uq_excepcion_profesional_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='es_demo',
            field=models.BooleanField(default=False, help_text='Establecimiento ficticio de demostración pública. Exento de suspensión, con panel espejo abierto y datos borrados periódicamente.'),
        ),
        migrations.AddIndex(
            model_name='establecimiento',
            index=models.Index(condition=models.Q(('es_demo', True)), fields=['es_demo'], name='idx_establecimiento_demo'),
        ),
    ]
