# Generated by Django 4.2.30 on 2026-09-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0012_establecimiento_es_demo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefinal',
            name='telefono_revisar',
            field=models.BooleanField(default=False, help_text='El teléfono no tiene 10 dígitos y necesita corrección manual.'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='telefono_revisar',
            field=models.BooleanField(default=False, help_text='El teléfono no tiene 10 dígitos y necesita corrección manual.'),
        ),
    ]
