# Generated by Django 4.2.30 on 2026-06-12 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada_cliente', 'Cancelada por el cliente'), ('cancelada_profesional', 'Cancelada por el profesional'), ('completada', 'Completada'), ('no_asistio', 'No asistió')], default='confirmada', max_length=25)),
                ('canal', models.CharField(choices=[('ia', 'Asistente IA'), ('manual', 'Manual (panel)')], default='ia', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cancelacion_a_profesional', 'Cancelación → profesional'), ('cancelacion_masiva_a_cliente', 'Cancelación masiva → cliente'), ('recordatorio', 'Recordatorio → cliente')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('generada', 'Generada (enlace wa.me)'), ('enviada', 'Enviada')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='agenda.cita')),
            ],
            options={
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notificacion',
            },
        ),
    ]
