# Generated by Django 4.2.30 on 2026-06-12 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='negocios.clientefinal'),
        ),
        migrations.AddField(
            model_name='cita',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='negocios.establecimiento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='negocios.profesional'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='negocios.servicio'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['profesional', 'fecha'], name='idx_cita_agenda'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['establecimiento', 'fecha'], name='idx_cita_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_cita_fin_mayor_inicio'),
        ),
    ]
