# Generated by Django 4.2.30 on 2026-08-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_exclusion_anti_solape'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'recordatorio')), fields=('cita',), name='uq_un_recordatorio_por_cita'),
        ),
    ]
