# Generated by Django 4.2.30 on 2026-09-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_notificacion_uq_un_recordatorio_por_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='serie',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
