# Generated by Django 4.2.30 on 2026-09-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_cita_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='canal',
            field=models.CharField(choices=[('ia', 'Asistente IA'), ('manual', 'Manual (panel)'), ('web', 'Autoservicio web')], default='ia', max_length=10),
        ),
    ]
