# Generated by Django 4.2.30 on 2026-07-25 21:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('prueba', 'En período de prueba'), ('activa', 'Activa'), ('suspendida', 'Suspendida por falta de pago'), ('cancelada', 'Cancelada')], db_index=True, default='prueba', max_length=20)),
                ('fecha_inicio_prueba', models.DateField()),
                ('fecha_fin_prueba', models.DateField(help_text='Fin de los 14 días de prueba. Informativo tras el primer pago.')),
                ('dia_corte', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes que ancla el ciclo, fijado en el primer pago confirmado (topado en 28 para evitar meses cortos). En el piloto es informativo; en v1.1 anclará el cobro automático.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('fecha_vencimiento_actual', models.DateField(db_index=True, help_text='Fuente única de verdad del acceso. El establecimiento tiene servicio mientras hoy <= esta fecha y el estado no sea suspendida/cancelada.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('establecimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='negocios.establecimiento')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
                'db_table': 'suscripcion',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Período que cubre el pago, en formato AAAA-MM (ej. 2026-08).', max_length=7)),
                ('monto', models.DecimalField(decimal_places=0, help_text='Monto en pesos colombianos, derivado del plan del establecimiento.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo', models.CharField(choices=[('nequi', 'Nequi'), ('daviplata', 'Daviplata')], max_length=20)),
                ('comprobante', models.ImageField(help_text='Imagen del comprobante de la transacción. Se persiste en Cloudinary.', upload_to='comprobantes/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente_verificacion', 'Pendiente de verificación'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente_verificacion', max_length=25)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Explicación visible para el establecimiento cuando se rechaza.')),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(blank=True, help_text='Superadmin que verificó el comprobante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='facturacion.suscripcion')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'confirmado')), fields=('suscripcion', 'periodo'), name='uq_pago_confirmado_periodo'),
        ),
    ]
