# Generated by Django 4.2.30 on 2026-08-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('breb', 'Bre-B (desde cualquier banco)'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], max_length=20),
        ),
    ]
