# Generated by Django 4.2.30 on 2026-08-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='aplicado',
            field=models.BooleanField(default=False, help_text='La extension optimista de este pago sigue vigente.'),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado_previo',
            field=models.CharField(blank=True, help_text='Estado de la suscripcion antes de aplicar la extension.', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='vencimiento_previo',
            field=models.DateField(blank=True, help_text='Vencimiento antes de aplicar la extension, para revertir.', null=True),
        ),
    ]
